language: python

python:
  - '3.4'
  - '3.5'

before_install:
  - pip install --upgrade pip
  - pip install pylama
  - sudo pip install lizard

install:
  - pip install -r requirments.txt

script:
  - pylama skygear
  - python setup.py test
  - lizard skygear -C 10 -w -i 0

notifications:
  slack: oursky:PxqsclRADehuWEs51vpgxeUh
