language: python

sudo: false

python:
  - '3.4'
  - '3.5'

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install --upgrade pip
  - pip install pylama
  - pip install isort
  - pip install lizard

install:
  - pip install -r requirments.txt

script:
  - pylama skygear
  - python setup.py test
  - python "`which lizard`" skygear -C 10 -w -i 0

notifications:
  slack: oursky:PxqsclRADehuWEs51vpgxeUh
