language: python

sudo: false

python:
  - '3.4'
  - '3.5'

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.cache/pip

env:
  - DATABASE_URL=postgresql://postgres:@localhost/skygear_test?sslmode=disable

before_install:
  - pip install --upgrade pip
  - pip install pylama
  - pip install isort
  - pip install lizard
  - pip install coverage

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'CREATE DATABASE skygear_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d skygear_test

script:
  - pylama skygear
  - coverage run --source skygear setup.py test
  - python "`which lizard`" skygear -C 10 -w -i 0
  - coverage report -m

notifications:
  slack: oursky:PxqsclRADehuWEs51vpgxeUh
